version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/edwarnicke/pkgcloud
    steps:
      - checkout
      - run: go build .
